#!/usr/bin/env bash

if [ "$GOJIRA_DATABASE" == 'cassandra' ]; then
    p_compose exec db cqlsh ${EXTRA_ARGS:--k kong}
elif [ "$GOJIRA_DATABASE" == 'postgres' ]; then
    p_compose exec db psql ${EXTRA_ARGS:--U kong -d kong}
fi
