#!/usr/bin/env bash

cat << EOF
version: '3.5'
services:
  ${GOJIRA_TARGET:-kong}:
    environment:
      KONG_PG_HOST: ${KONG_PG_HOST:-localhost}
      KONG_CASSANDRA_CONTACT_POINTS: ${KONG_CASSANDRA_CONTACT_POINTS:-localhost}
      KONG_REDIS_HOST: ${KONG_REDIS_HOST:-localhost}

      KONG_TEST_PG_HOST: ${KONG_PG_HOST:-localhost}
      KONG_TEST_CASSANDRA_CONTACT_POINTS: ${KONG_CASSANDRA_CONTACT_POINTS:-localhost}
      KONG_SPEC_TEST_REDIS_HOST: ${KONG_SPEC_TEST_REDIS_HOST:-localhost}
      KONG_SPEC_TEST_REDIS_PORT: ${KONG_SPEC_TESR_REDIS_PORTT:-6379}
      KONG_SPEC_TEST_REDIS_SSL_PORT: ${KONG_SPEC_TESR_REDIS_SSL_PORT:-6380}
      KONG_SPEC_TEST_REDIS_SSL_SNI: ${KONG_SPEC_TESR_REDIS_SSL_SNI:-test-redis.example.com}
EOF
