---
name: Pull Request Labeler

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  autolabel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: TimonVS/pr-labeler-action@v3.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
