---
name: Build

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: gojira
